### ISSUE TITLE
website content and sectioning

### ISSUE THREAD

**Issue by nell-byler** [astroDJC/suggestedposts#12]
This is half a question about the blogger format and half a suggestion for other github posts.

It might be nice to have general "resources" section (or sidebar)? with links to sites/blogs we find informative, books to check out from the library or buy on amazon, podcasts to subscribe to, with the list maintained via github.

We should probably put some thought what we do/don't link to, to make sure that the resources stay appropriately close to the mission of astroDJC (which is still sort of nebulous at this stage).

**Comment by sjschmidt** [comment]
I agree - there are some resources I collected here: http://www.astronomy.ohio-state.edu/~schmidt/DiversityResources.html and some from the astrobetter wiki here: http://www.astrobetter.com/wiki/Diversity that could be good starting off points. 

On a slightly more meta level - can we maybe have a categories here for putting together non-post blog content (about, resources, blogroll, compiled units, whatever)? Then we could accept input from others and iterate amongst ourselves?

**Comment by sjschmidt** [comment]
Oh, and a glossary/index maybe?

**Comment by nell-byler** [comment]
yes! a glossary/index is a fantastic idea.

**Comment by nell-byler** [comment]
thanks for the links to the resources!
On the meta comment - do you mean more folders in the repository on the level of "suggested posts"? ( i don't think I know what blogroll means, though.) Or do you mean as "issue subjects" so people can easily reply to them there in a more conversational means?

**Comment by bmorris3** [comment]
We could have a wiki page for that purpose, which anyone can edit. [I've created one here to fill in](https://github.com/astroDJC/suggestedposts/wiki/Resources).

I think the most general way to accept non-post blog content is in the issues, like you're doing here.

**Comment by bmorris3** [comment]
Thanks for the big update @sjschmidt !
