### ISSUE TITLE
I'm having trouble starting a new post.

### ISSUE THREAD

**Issue by sjschmidt** [astroDJC/suggestedposts#15]
So I was trying to write a new post and had trouble with the wiki. I followed the instructions and was editing the template text in my new file, but when I went to save it, the options weren't described by the wiki instructions. As you see below, I don't get a "propose file change" button - instead I have a "commit directly to master branch." Is that what I'm supposed to do?

Also, I find the whole copying template text and pasting into a new file pretty clunky. Can't we just do some sort of save as a new file (but in some fancy git way)?

![screen shot 2015-06-14 at 12 28 14 pm 2](https://cloud.githubusercontent.com/assets/1139537/8149457/e23b98fa-1291-11e5-8c77-3257448b6ab3.png)

**Comment by bmorris3** [comment]
You have a different option there because you are a Collaborator on this project, and your special permissions allow you to update the file without offering a pull request (like everyone else must). If you'd like, I can remove your special privileges (which won't affect your ability to post in any way other than changing the functionality of those buttons) and you can see if the tutorial works.

> Also, I find the whole copying template text and pasting into a new file pretty clunky.

I feel like it's a bit clunky too, but for now this is the most hassle-free way of in-browser editing that I can think of. I'll keep searching for better ways, but if you beat me to it, please let me know if you find anything better.

**Comment by sjschmidt** [comment]
Ha! Well, then my real problem is that I still don't know what button to push. Is it just leave "commit to master branch" selected and then the green button?

**Comment by bmorris3** [comment]
Would you mind if I down-graded your privileges to see if you can follow along the tutorial without issue? It would be a good beta test. 

For future reference though, to retain the old functionality with your privileges, you should select the second radio button to "Create a new branch", which will give you the "Propose New File" button that you were expecting.
![screen shot 2015-06-15 at 12 07 05 pm](https://cloud.githubusercontent.com/assets/3497584/8168047/113f2872-1357-11e5-8494-e15323270031.png)

**Comment by sjschmidt** [comment]
Sure! I have some time to try it again in about an hour.

-sarah

On Mon, Jun 15, 2015 at 3:08 PM, Brett M. Morris notifications@github.com
wrote:

> Would you mind if I down-graded your privileges to see if you can follow
> along the tutorial without issue? It would be a good beta test.
> 
> For future reference though, to retain the old functionality with your
> privileges, you should select the second radio button to "Create a new
> branch", which will give you the "Propose New File" button that you were
> expecting.
> [image: screen shot 2015-06-15 at 12 07 05 pm]
> https://cloud.githubusercontent.com/assets/3497584/8168047/113f2872-1357-11e5-8494-e15323270031.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/astroDJC/suggestedposts/issues/15#issuecomment-112176805
> .

## 

Sarah Jane Schmidt, PhD

schmidt@astronomy.ohio-state.edu
http://www.astronomy.ohio-state.edu/~schmidt/
Columbus Prize Fellow
Astronomy Department
The Ohio State University

**Comment by bmorris3** [comment]
You're now no longer an organizer. Give it a shot when you get a chance!

**Comment by sjschmidt** [comment]
Ok - the text still says "propose new file" instead of "propose file change" but everything else looked good.

**Comment by sjschmidt** [comment]
Oh, though I would add a screenshot (I can take one with the right buttons when i write the next post) and I might also have another couple points that discuss logging back in to edit the post!

**Comment by bmorris3** [comment]
> the text still says "propose new file" instead of "propose file change"

Thanks for the wording correction, I've changed the [wiki](https://github.com/astroDJC/suggestedposts/wiki). If you see anything else in there that needs tweaking, you should be able to edit the wiki page with the Edit button in the upper right corner.

**Comment by sjschmidt** [comment]
Cool. Mostly I didn't make that one because I wasn't sure if I was doing something wrong! I grabbed a screenshot of how that button looks from the outside, so I think I've done it all I meant to while not an organizer (unless there's something else I should test)!

**Comment by bmorris3** [comment]
I think the last thing to test is editing a post. I left a comment on your pull request for a typo correction – is it straightforward for you to figure out how to do that? We could use a section in the tutorial on corrections/updates.

**Comment by sjschmidt** [comment]
Um... I have no idea how to do that. I've clicked the links in both of the emails I got about the post. I can see the post, and I can see your comment, but I don't know what I'm supposed to do and as far as I know I can't actually edit my post?

**Comment by bmorris3** [comment]
@nell-byler : What did you find was the most convenient way to edit a file after you've started a pull request? @sjschmidt made PR #16 which we'd like to correct. 

@sjschmidt : The way I would do it is like this: 
- When you created the new file, GitHub "forked" the repository, so on your GitHub account you can see a repository called sjschmidt/suggested_posts/ which has your [post draft in it at this location](https://github.com/sjschmidt/suggestedposts/blob/patch-1/merged_posts/Schmidt20150615.md)
- Click the pencil icon in the upper right will allow you to change the post.
- Check back at the PR #16 page to see if the new commit is added with the correction.

**Comment by sjschmidt** [comment]
Ok. So the only way I can seem to find my post is through the link you gave me. When I go to my account and find sjschmidt/suggestedposts/merged_posts it only lists nell's and the post_template.md. When I click the link you sent, it takes me where i want to go to fix that typo.

**Comment by sjschmidt** [comment]
(fyi, heading out of the office - I will pick this up tonight or tomorrow morning)

**Comment by bmorris3** [comment]
> So the only way I can seem to find my post is through the link you gave me. 

I'm looking for a way of making this more simple to get access to, but I'll expand on the whole story here. This explanation will be more intimidating than I'd want any tutorial to be.

When you look at your [sjschmidt/suggestedposts](https://github.com/sjschmidt/suggestedposts) repository, by default you're looking at the "master" branch, but the suggested change that you made is stuck into the "[patch-1](https://github.com/sjschmidt/suggestedposts/tree/patch-1)" branch by default, to keep the revision control history organized. To switch to between these branches, there's a dropdown menu with a silver button under the "36 commits" counter near the top left of your [sjschmidt/suggestedposts repo](https://github.com/sjschmidt/suggestedposts). When you're on the master branch this button says "branch: master". If you select patch-1, then the version of the repository that you're looking at will be the one with your suggested change. 

From there, you can navigate into the merged_posts directory to open your post, and edit it with the pencil icon in the upper right.

**Comment by sjschmidt** [comment]
Ok. I read this 24 hours ago, and then was able to find the post without referring back to it. I think I clicked slightly differently - my account, suggested posts, branches, patch-1, merged-posts, then it was there! Maybe until we get a chance to wiki-fy that (or the easier way you described), we can just default to responding to new submissions with "here is a direct link to edit" (at least, when we aren't sure if someone knows how)?

**Comment by bmorris3** [comment]
Sounds good. If there are no other comments and you're ready to end this issue, click close below.
